### ISSUE TITLE
pip install requesments.txt error

### ISSUE THREAD

**Issue by t0ny117** [ebubekirbbr/dephides#1]
I would like to know how to download requesments.txt, this file in your repository seems to have changed to fit lfs format, pip install can't use it directly, I would like to know how I should download it correctly!

**Comment by t0ny117** [comment]
The above problem occurs because I downloaded the project zip directly, so the dataset and pip dependency files are all oid sha256 pointers to git lfs, I tried to download git and git lfs locally and pull the project directly from powershell using git clone, but the following error occurs:
Error downloading object: dataset/big_dataset/meta.txt (f632acb): Smudge error: Error downloading dataset/big_dataset/meta.txt ( f632acbbaf90369e034df24d185fdaf4897a5c63af6fea37a22b52802e4f45bb): batch response: This repository is over its data quota. account responsible for LFS bandwidth should purchase more data packs to restore access.
I rarely use git lfs, I'm guessing that your lfs repository is running out of storage capacity, and thus causing the dataset download to fail. Dear author, can you solve this problem, this project is very important to me and I need it very much to pass my subject project, 555, please!

**Comment by ebubekirbbr** [comment]
If you have problems accessing the data set Request an access Google Drive link (https://drive.google.com/drive/folders/13zj-HYEmYAyScb1nd4Lf329VJIHIUvhv?usp=drive_link)
 
This info is available in Readme.md file also. So anyone can request an access to link. Thank you for attention. 
Please feel free to ask another question.

I will try to fix the issue. Until then you can use data set with this way.

Best

**Comment by BigRain02** [comment]
Can you share your requirements.txt? I want to run this repository, but i have trouble to set the version of the package cause your requirements.txt was blocked to download.

**Comment by ebubekirbbr** [comment]
Fixed!
